#include <QApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include "app/ApplicationController.h"

int main(int argc, char *argv[])
{
    // Do not reuse a QML disk cache generated by a previous executable.
    // This is particularly important while generated Quick3D rig files change.
    qputenv("QML_DISABLE_DISK_CACHE", "1");
    QApplication app(argc, argv);
    app.setApplicationName("DeskPet");
    app.setOrganizationName("DeskPet");

    ApplicationController controller;
    QQmlApplicationEngine engine;
    engine.rootContext()->setContextProperty("applicationController", &controller);
    engine.loadFromModule("DeskPet", "Main");
    if (engine.rootObjects().isEmpty()) return -1;
    return app.exec();
}
